spring:
  application:
    name: lookkit2nd
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  config:
    import: optional:file:.env[.properties]
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  http:
    encoding:
      charset: UTF-8
      enabled: true
  mvc:
    static-path-pattern: "/**"
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            scope:
              - profile_nickname
              - account_email
              - name
              - gender
              - birthday
              - birthyear
              - phone_number
            redirect-uri: ${KAKAO_REDIRECT_URL}
            client-name: kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        google:
          client-id: ${GOOGLE_CLIENT_ID}
          client-secret: ${GOOGLE_CLIENT_SECRET}
        naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
        github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}

server:
  port: 8081
  servlet:
    encoding:
      force-response: true
      charset: UTF-8
    session:
      timeout: 60m
      cookie:
        max-age: 60m

logging:
  level:
    org:
      springframework:
        web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG