name: Deploy To EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        env:
          APPLICATION_PROPERTIES: ${{ secrets.APPLICATION_PROPERTIES }}
          AXIOS_BASEURL: ${{ secrets.AXIOS_BASEURL }}
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        with:
          host: ${{ secrets.EC2_HOST }} # EC2의 주소
          username: ${{ secrets.EC2_USERNAME }} # EC2 접속 username
          key: ${{ secrets.EC2_PRIVATE_KEY }} # EC2의 Key 파일의 내부 텍스트
          envs: APPLICATION_PROPERTIES,AXIOS_BASEURL,FIREBASE_CONFIG
          script_stop: true # 아래 script 중 실패하는 명령이 하나라도 있으면 실패로 처리
          script: |
            cd /home/ubuntu/lookkit-ver2.0 # 여기 경로는 자신의 EC2에 맞는 경로로 재작성하기
            if [ -f frontend/src/api/axios.js ]; then
              rm -rf frontend/src/api/axios.js
            fi
            if [ -f frontend/src/firebase/firebaseConfig.js ]; then
              rm -rf frontend/src/firebase/firebaseConfig.js
            fi
            
            rm -rf src/main/resources/application.yml
            
            git pull origin main
            echo "$APPLICATION_PROPERTIES" > src/main/resources/application.yml
            echo "$AXIOS_BASEURL" > frontend/src/api/axios.js
            echo "$FIREBASE_CONFIG" > frontend/src/firebase/firebaseConfig.js
            echo "Gradle 빌드 시작..."
            ./gradlew clean build -x test
            sudo fuser -k -n tcp 8081 || true 
            
            # iptables-persistent 패키지 설치 (이미 설치되어 있어도 오류 발생 안함)
            echo "iptables-persistent iptables-persistent/autosave_v4 boolean true" | sudo debconf-set-selections
            echo "iptables-persistent iptables-persistent/autosave_v6 boolean true" | sudo debconf-set-selections
            sudo apt-get update -qq && sudo apt-get install -y -qq iptables-persistent
            
            # 포트포워딩 설정 - 기존 룰 삭제 후 새로 추가
            sudo iptables -t nat -D PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8081 || true
            sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8081
            
            # 포트포워딩 설정 저장 (영구적으로 적용)
            sudo netfilter-persistent save
            
            # 애플리케이션 실행
            nohup java -jar build/libs/lookkit2nd-0.0.1-SNAPSHOT.jar > ./output.log 2>&1 &